"""Add farm_type and experience columns to User model

Revision ID: 207b6c4c9658
Revises: 85b79f75a142
Create Date: 2025-05-17 17:01:38.556416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207b6c4c9658'
down_revision = '85b79f75a142'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('soil_report', schema=None) as batch_op:
        batch_op.drop_column('status')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('experience', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('experience')
        batch_op.drop_column('farm_type')

    with op.batch_alter_table('soil_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), nullable=True))

    # ### end Alembic commands ###
