"""Add wallet_balance to User model

Revision ID: 7bada89cbe8f
Revises: 
Create Date: 2025-05-17 11:11:01.408238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bada89cbe8f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gov_scheme', schema=None) as batch_op:
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=False)

    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.alter_column('investor_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet_balance', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('wallet_balance')

    with op.batch_alter_table('investment', schema=None) as batch_op:
        batch_op.alter_column('investor_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('gov_scheme', schema=None) as batch_op:
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
