"""Add quantity field to Transaction model

Revision ID: 85b79f75a142
Revises: 7bada89cbe8f
Create Date: 2025-05-17 11:20:58.688368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b79f75a142'
down_revision = '7bada89cbe8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
